project:
  type: book
  output-dir: docs

book:
  title: "I Shall Be Released"
  author: "Bob Dylan"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - any.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

